// Billing cycles are generated by ONE authoritative path: the database
// function sync_client_billing_cycles_authorized. Client code never
// reproduces the cycle rules — it asks the server to (re)build them, which
// also keeps manual claim/payment edits intact and stays permission-safe.
import { supabase } from '@/integrations/supabase/client';

export async function regenerateClientCycles(clientId: string): Promise<void> {
  const { error } = await supabase.rpc('sync_client_billing_cycles_authorized', {
    p_client_id: clientId,
  });
  if (error) throw new Error(error.message);
}


// Fetch active case managers (profiles), excluding superadmins.
export interface CaseManagerOption {
  id: string;
  first_name: string | null;
  last_name: string | null;
  email: string;
}

export async function fetchActiveCaseManagers(): Promise<CaseManagerOption[]> {
  const { data: profiles } = await supabase
    .from('profiles')
    .select('id, first_name, last_name, email, user_id')
    .eq('active', true)
    .order('first_name');

  const { data: superRoles } = await supabase
    .from('user_roles')
    .select('user_id')
    .eq('role', 'superadmin');
  const superIds = new Set((superRoles || []).map((r) => r.user_id));

  return (profiles || [])
    .filter((p) => !superIds.has((p as { user_id: string }).user_id))
    .map((p) => ({ id: p.id, first_name: p.first_name, last_name: p.last_name, email: p.email }));
}

export function caseManagerName(cm: { first_name: string | null; last_name: string | null; email: string }): string {
  const full = `${cm.first_name ?? ''} ${cm.last_name ?? ''}`.trim();
  return full || cm.email;
}
