// Generated by scripts/move-in/uhc-layout.py from UHC's Move-In Supports
// Checklist. Do not edit by hand: change the script and run it again.
//
// Each line names the cells it is written to in UHC's own spreadsheet
// (public/form-templates/uhc-move-in-supports.xlsx). 445 lines.
import type { UhcTab } from './types';

export const MEMBER_SHEET = 'xl/worksheets/sheet1.xml';
export const MEMBER_CELLS = {
  "provider": "C6",
  "caseManager": "C7",
  "cmPhone": "C8",
  "cmEmail": "C9",
  "memberName": "C11",
  "medicaidId": "C12",
  "householdSize": "C13",
  "newAddress": "C14",
  "memberPhone": "C15",
  "moveInDate": "C16",
  "emergencyContact": "B18",
  "delivery": "B20"
} as const;
export const GRAND_TOTAL_CELL = 'F22';

export const UHC_TABS: UhcTab[] = [
  {
    "id": "services",
    "title": "Services",
    "sheet": "xl/worksheets/sheet2.xml",
    "totalCell": "C28",
    "sections": [
      {
        "title": "Residence Fees",
        "lines": [
          {
            "id": "services.application_fee",
            "label": "Application Fee",
            "cell": "B3",
            "total": "C3",
            "note": true,
            "noteLabel": "Property name",
            "text": "Application Fee (List Property Name if applicable):"
          },
          {
            "id": "services.security_deposit",
            "label": "Security Deposit",
            "cell": "B4",
            "total": "C4"
          },
          {
            "id": "services.other_home_deposit",
            "label": "Other Home Deposit",
            "cell": "B7",
            "total": "C7",
            "note": true,
            "noteLabel": "What the deposit is for",
            "text": "Other home deposits (Please specify)-"
          }
        ]
      },
      {
        "title": "Utilities Deposits",
        "lines": [
          {
            "id": "services.water",
            "label": "Water",
            "cell": "B9",
            "total": "C9"
          },
          {
            "id": "services.gas",
            "label": "Gas",
            "cell": "B10",
            "total": "C10"
          },
          {
            "id": "services.electricity",
            "label": "Electricity",
            "cell": "B11",
            "total": "C11"
          },
          {
            "id": "services.telephone",
            "label": "Telephone",
            "cell": "B12",
            "total": "C12"
          },
          {
            "id": "services.oil",
            "label": "Oil",
            "cell": "B13",
            "total": "C13"
          },
          {
            "id": "services.propane",
            "label": "Propane",
            "cell": "B14",
            "total": "C14"
          },
          {
            "id": "services.garbage_sewage_service",
            "label": "Garbage/Sewage Service",
            "cell": "B15",
            "total": "C15"
          },
          {
            "id": "services.other",
            "label": "Other",
            "cell": "B16",
            "total": "C16",
            "note": true,
            "noteLabel": "Which utility",
            "text": "*Other"
          }
        ]
      },
      {
        "title": "Moving Company",
        "lines": [
          {
            "id": "services.moving_company",
            "label": "Moving Company",
            "cell": "B17",
            "total": "C17",
            "note": true,
            "noteLabel": "Company name",
            "text": "Moving Company (List name if applicable)"
          }
        ]
      },
      {
        "title": "Identification Documents",
        "lines": [
          {
            "id": "services.birth_certficate",
            "label": "Birth Certficate",
            "cell": "B20",
            "total": "C20"
          },
          {
            "id": "services.state_id",
            "label": "State ID",
            "cell": "B21",
            "total": "C21"
          },
          {
            "id": "services.marriage_license",
            "label": "Marriage License",
            "cell": "B22",
            "total": "C22"
          },
          {
            "id": "services.other_2",
            "label": "Other",
            "cell": "B23",
            "total": "C23",
            "note": true,
            "noteLabel": "Which document",
            "text": "Other"
          }
        ]
      }
    ]
  },
  {
    "id": "food",
    "title": "Food",
    "sheet": "xl/worksheets/sheet3.xml",
    "totalCell": "I148",
    "sections": [
      {
        "title": "Vegetables",
        "lines": [
          {
            "id": "food.asparagus",
            "label": "Asparagus",
            "cell": "B3",
            "qty": "A3",
            "total": "C3"
          },
          {
            "id": "food.carrots",
            "label": "Carrots",
            "cell": "E3",
            "qty": "D3",
            "total": "F3"
          },
          {
            "id": "food.cucumber",
            "label": "Cucumber",
            "cell": "H3",
            "qty": "G3",
            "total": "I3"
          },
          {
            "id": "food.cabbage",
            "label": "Cabbage",
            "cell": "B4",
            "qty": "A4",
            "total": "C4"
          },
          {
            "id": "food.corn",
            "label": "Corn",
            "cell": "E4",
            "qty": "D4",
            "total": "F4"
          },
          {
            "id": "food.celery",
            "label": "Celery",
            "cell": "B5",
            "qty": "A5",
            "total": "C5"
          },
          {
            "id": "food.lettuce",
            "label": "Lettuce",
            "cell": "E5",
            "qty": "D5",
            "total": "F5"
          },
          {
            "id": "food.potatoes",
            "label": "Potatoes",
            "cell": "H5",
            "qty": "G5",
            "total": "I5"
          },
          {
            "id": "food.eggplant",
            "label": "Eggplant",
            "cell": "B6",
            "qty": "A6",
            "total": "C6"
          },
          {
            "id": "food.peppers",
            "label": "Peppers",
            "cell": "E6",
            "qty": "D6",
            "total": "F6"
          },
          {
            "id": "food.tomatoes",
            "label": "Tomatoes",
            "cell": "H6",
            "qty": "G6",
            "total": "I6"
          },
          {
            "id": "food.onions",
            "label": "Onions",
            "cell": "B7",
            "qty": "A7",
            "total": "C7"
          },
          {
            "id": "food.squash",
            "label": "Squash",
            "cell": "E7",
            "qty": "D7",
            "total": "F7"
          },
          {
            "id": "food.brussels_sprouts",
            "label": "Brussels Sprouts",
            "cell": "H7",
            "qty": "G7",
            "total": "I7"
          },
          {
            "id": "food.spinach",
            "label": "Spinach",
            "cell": "B8",
            "qty": "A8",
            "total": "C8"
          },
          {
            "id": "food.broccoli",
            "label": "Broccoli",
            "cell": "E8",
            "qty": "D8",
            "total": "F8"
          },
          {
            "id": "food.garlic",
            "label": "Garlic",
            "cell": "H8",
            "qty": "G8",
            "total": "I8"
          },
          {
            "id": "food.zucchini",
            "label": "Zucchini",
            "cell": "B9",
            "qty": "A9",
            "total": "C9"
          },
          {
            "id": "food.cauliflower",
            "label": "Cauliflower",
            "cell": "E9",
            "qty": "D9",
            "total": "F9"
          }
        ]
      },
      {
        "title": "Fruits",
        "lines": [
          {
            "id": "food.apples_bag",
            "label": "Apples bag",
            "cell": "B11",
            "qty": "A11",
            "total": "C11"
          },
          {
            "id": "food.avocados",
            "label": "Avocados",
            "cell": "E11",
            "qty": "D11",
            "total": "F11"
          },
          {
            "id": "food.bananas",
            "label": "Bananas",
            "cell": "H11",
            "qty": "G11",
            "total": "I11"
          },
          {
            "id": "food.berries",
            "label": "Berries",
            "cell": "B12",
            "qty": "A12",
            "total": "C12"
          },
          {
            "id": "food.cantelope",
            "label": "Cantelope",
            "cell": "E12",
            "qty": "D12",
            "total": "F12"
          },
          {
            "id": "food.cherries",
            "label": "Cherries",
            "cell": "H12",
            "qty": "G12",
            "total": "I12"
          },
          {
            "id": "food.grapefruit",
            "label": "Grapefruit",
            "cell": "B13",
            "qty": "A13",
            "total": "C13"
          },
          {
            "id": "food.grapes_red_or_green",
            "label": "Grapes",
            "cell": "E13",
            "qty": "D13",
            "total": "F13",
            "note": true,
            "noteLabel": "Red or Green",
            "text": "Grapes: Red or Green"
          },
          {
            "id": "food.kiwi",
            "label": "Kiwi",
            "cell": "H13",
            "qty": "G13",
            "total": "I13"
          },
          {
            "id": "food.lemons",
            "label": "Lemons",
            "cell": "B14",
            "qty": "A14",
            "total": "C14"
          },
          {
            "id": "food.limes",
            "label": "Limes",
            "cell": "E14",
            "qty": "D14",
            "total": "F14"
          },
          {
            "id": "food.mangos",
            "label": "Mangos",
            "cell": "H14",
            "qty": "G14",
            "total": "I14"
          },
          {
            "id": "food.nectarines",
            "label": "Nectarines",
            "cell": "B15",
            "qty": "A15",
            "total": "C15"
          },
          {
            "id": "food.oranges",
            "label": "Oranges",
            "cell": "E15",
            "qty": "D15",
            "total": "F15"
          },
          {
            "id": "food.pineapple",
            "label": "Pineapple",
            "cell": "H15",
            "qty": "G15",
            "total": "I15"
          },
          {
            "id": "food.papaya",
            "label": "Papaya",
            "cell": "B16",
            "qty": "A16",
            "total": "C16"
          },
          {
            "id": "food.peaches",
            "label": "Peaches",
            "cell": "E16",
            "qty": "D16",
            "total": "F16"
          },
          {
            "id": "food.pears",
            "label": "Pears",
            "cell": "H16",
            "qty": "G16",
            "total": "I16"
          },
          {
            "id": "food.plum",
            "label": "Plum",
            "cell": "B17",
            "qty": "A17",
            "total": "C17"
          },
          {
            "id": "food.watermelon",
            "label": "Watermelon",
            "cell": "E17",
            "qty": "D17",
            "total": "F17"
          },
          {
            "id": "food.apricots",
            "label": "Apricots",
            "cell": "H17",
            "qty": "G17",
            "total": "I17"
          },
          {
            "id": "food.grapefruit_2",
            "label": "Grapefruit",
            "cell": "B18",
            "qty": "A18",
            "total": "C18"
          }
        ]
      },
      {
        "title": "Condiments",
        "lines": [
          {
            "id": "food.bbq_sauce",
            "label": "BBQ Sauce",
            "cell": "B20",
            "qty": "A20",
            "total": "C20"
          },
          {
            "id": "food.gravy",
            "label": "Gravy",
            "cell": "E20",
            "qty": "D20",
            "total": "F20"
          },
          {
            "id": "food.honey",
            "label": "Honey",
            "cell": "H20",
            "qty": "G20",
            "total": "I20"
          },
          {
            "id": "food.hot_sauce",
            "label": "Hot Sauce",
            "cell": "B21",
            "qty": "A21",
            "total": "C21"
          },
          {
            "id": "food.jam_or_jelly",
            "label": "Jam OR Jelly",
            "cell": "E21",
            "qty": "D21",
            "total": "F21",
            "note": true,
            "noteLabel": "Which one",
            "text": "Jam OR Jelly"
          },
          {
            "id": "food.ketchup",
            "label": "Ketchup",
            "cell": "H21",
            "qty": "G21",
            "total": "I21"
          },
          {
            "id": "food.mustard",
            "label": "Mustard",
            "cell": "B22",
            "qty": "A22",
            "total": "C22"
          },
          {
            "id": "food.mayonnaise",
            "label": "Mayonnaise",
            "cell": "E22",
            "qty": "D22",
            "total": "F22"
          },
          {
            "id": "food.relish",
            "label": "Relish",
            "cell": "H22",
            "qty": "G22",
            "total": "I22"
          },
          {
            "id": "food.salad_dressing_type",
            "label": "Salad Dressing",
            "cell": "B23",
            "qty": "A23",
            "total": "C23",
            "note": true,
            "noteLabel": "Type",
            "text": "Salad Dressing: Type"
          },
          {
            "id": "food.steak_sauce",
            "label": "Steak Sauce",
            "cell": "E23",
            "qty": "D23",
            "total": "F23"
          },
          {
            "id": "food.syrup",
            "label": "Syrup",
            "cell": "H23",
            "qty": "G23",
            "total": "I23"
          },
          {
            "id": "food.worcestershire_sauce",
            "label": "Worcestershire Sauce",
            "cell": "E24",
            "qty": "D24",
            "total": "F24"
          },
          {
            "id": "food.soy_sauce",
            "label": "Soy Sauce",
            "cell": "H24",
            "qty": "G24",
            "total": "I24"
          },
          {
            "id": "food.salsa",
            "label": "Salsa",
            "cell": "B25",
            "qty": "A25",
            "total": "C25"
          }
        ]
      },
      {
        "title": "Dairy",
        "lines": [
          {
            "id": "food.butter_or_margarine",
            "label": "Butter or Margarine",
            "cell": "B27",
            "qty": "A27",
            "total": "C27",
            "note": true,
            "noteLabel": "Which one",
            "text": "Butter or Margarine"
          },
          {
            "id": "food.eggs",
            "label": "Eggs",
            "cell": "E27",
            "qty": "D27",
            "total": "F27"
          },
          {
            "id": "food.cottage_cheese",
            "label": "Cottage Cheese",
            "cell": "H27",
            "qty": "G27",
            "total": "I27"
          },
          {
            "id": "food.half_half",
            "label": "Half & Half",
            "cell": "B28",
            "qty": "A28",
            "total": "C28"
          },
          {
            "id": "food.milk_type",
            "label": "Milk",
            "cell": "E28",
            "qty": "D28",
            "total": "F28",
            "note": true,
            "noteLabel": "Type",
            "text": "Milk Type:"
          },
          {
            "id": "food.evaporated_milk",
            "label": "Evaporated Milk",
            "cell": "H28",
            "qty": "G28",
            "total": "I28"
          },
          {
            "id": "food.coconut_milk",
            "label": "Coconut Milk",
            "cell": "B29",
            "qty": "A29",
            "total": "C29"
          },
          {
            "id": "food.sour_cream",
            "label": "Sour Cream",
            "cell": "E29",
            "qty": "D29",
            "total": "F29"
          },
          {
            "id": "food.whipped_cream",
            "label": "Whipped Cream",
            "cell": "H29",
            "qty": "G29",
            "total": "I29"
          },
          {
            "id": "food.yogurt_flavor",
            "label": "Yogurt",
            "cell": "B30",
            "qty": "A30",
            "total": "C30",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Yogurt Flavor:"
          },
          {
            "id": "food.cream_cheese",
            "label": "Cream Cheese",
            "cell": "E30",
            "qty": "D30",
            "total": "F30"
          }
        ]
      },
      {
        "title": "Cheese",
        "lines": [
          {
            "id": "food.cheddar_block",
            "label": "block",
            "cell": "B34",
            "qty": "A34",
            "total": "C34",
            "group": "Cheddar"
          },
          {
            "id": "food.feta",
            "label": "Feta",
            "cell": "E34",
            "qty": "D34",
            "total": "F34"
          },
          {
            "id": "food.cheese_form_block",
            "label": "Block",
            "cell": "H34",
            "qty": "G34",
            "total": "I34",
            "group": "Cheese form"
          },
          {
            "id": "food.cheddar_shredded",
            "label": "shredded",
            "cell": "B35",
            "qty": "A35",
            "total": "C35",
            "group": "Cheddar"
          },
          {
            "id": "food.mozzarella",
            "label": "Mozzarella",
            "cell": "E35",
            "qty": "D35",
            "total": "F35"
          },
          {
            "id": "food.cheese_form_shredded",
            "label": "Shredded",
            "cell": "H35",
            "qty": "G35",
            "total": "I35",
            "group": "Cheese form"
          },
          {
            "id": "food.cheddar_lunch",
            "label": "lunch",
            "cell": "B36",
            "qty": "A36",
            "total": "C36",
            "group": "Cheddar"
          },
          {
            "id": "food.provolone",
            "label": "Provolone",
            "cell": "E36",
            "qty": "D36",
            "total": "F36"
          },
          {
            "id": "food.cheese_form_sliced_lunch",
            "label": "Sliced/Lunch",
            "cell": "H36",
            "qty": "G36",
            "total": "I36",
            "group": "Cheese form"
          },
          {
            "id": "food.cheddar_sharp_sliced",
            "label": "sharp/ sliced",
            "cell": "B37",
            "qty": "A37",
            "total": "C37",
            "group": "Cheddar"
          },
          {
            "id": "food.blue_cheese",
            "label": "Blue Cheese",
            "cell": "E37",
            "qty": "D37",
            "total": "F37"
          },
          {
            "id": "food.cheese_form_ball",
            "label": "Ball",
            "cell": "H37",
            "qty": "G37",
            "total": "I37",
            "group": "Cheese form"
          },
          {
            "id": "food.cheddar_mild",
            "label": "mild",
            "cell": "B38",
            "qty": "A38",
            "total": "C38",
            "group": "Cheddar"
          },
          {
            "id": "food.american",
            "label": "American",
            "cell": "E38",
            "qty": "D38",
            "total": "F38"
          },
          {
            "id": "food.cheese_form_crumble",
            "label": "Crumble",
            "cell": "H38",
            "qty": "G38",
            "total": "I38",
            "group": "Cheese form"
          },
          {
            "id": "food.goat",
            "label": "Goat",
            "cell": "E39",
            "qty": "D39",
            "total": "F39"
          },
          {
            "id": "food.parmesan",
            "label": "Parmesan",
            "cell": "E40",
            "qty": "D40",
            "total": "F40"
          },
          {
            "id": "food.ricotta",
            "label": "Ricotta",
            "cell": "E41",
            "qty": "D41",
            "total": "F41"
          },
          {
            "id": "food.swiss",
            "label": "Swiss",
            "cell": "E42",
            "qty": "D42",
            "total": "F42"
          }
        ]
      },
      {
        "title": "Seafood",
        "lines": [
          {
            "id": "food.tilapia",
            "label": "Tilapia",
            "cell": "B44",
            "qty": "A44",
            "total": "C44"
          },
          {
            "id": "food.mussels",
            "label": "Mussels",
            "cell": "E44",
            "qty": "D44",
            "total": "F44"
          },
          {
            "id": "food.salmon",
            "label": "Salmon",
            "cell": "H44",
            "qty": "G44",
            "total": "I44"
          },
          {
            "id": "food.shrimp",
            "label": "Shrimp",
            "cell": "B45",
            "qty": "A45",
            "total": "C45"
          },
          {
            "id": "food.cod",
            "label": "Cod",
            "cell": "E45",
            "qty": "D45",
            "total": "F45"
          },
          {
            "id": "food.white_fish",
            "label": "White Fish",
            "cell": "H45",
            "qty": "G45",
            "total": "I45"
          }
        ]
      },
      {
        "title": "Frozen",
        "lines": [
          {
            "id": "food.fries",
            "label": "Fries",
            "cell": "B47",
            "qty": "A47",
            "total": "C47"
          },
          {
            "id": "food.ice_cream",
            "label": "Ice Cream",
            "cell": "E47",
            "qty": "D47",
            "total": "F47"
          },
          {
            "id": "food.burritos_flavor",
            "label": "Burritos",
            "cell": "H47",
            "qty": "G47",
            "total": "I47",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Burritos - Flavor:"
          },
          {
            "id": "food.pizza",
            "label": "Pizza",
            "cell": "B48",
            "qty": "A48",
            "total": "C48"
          },
          {
            "id": "food.fish_sticks",
            "label": "Fish Sticks",
            "cell": "E48",
            "qty": "D48",
            "total": "F48"
          },
          {
            "id": "food.tater_tots",
            "label": "Tater Tots",
            "cell": "H48",
            "qty": "G48",
            "total": "I48"
          },
          {
            "id": "food.tv_dinner_type",
            "label": "TV Dinner",
            "cell": "B49",
            "qty": "A49",
            "total": "C49",
            "note": true,
            "noteLabel": "Type",
            "text": "TV Dinner: type"
          },
          {
            "id": "food.waffles",
            "label": "Waffles",
            "cell": "E49",
            "qty": "D49",
            "total": "F49"
          },
          {
            "id": "food.pancakes",
            "label": "Pancakes",
            "cell": "H49",
            "qty": "G49",
            "total": "I49"
          },
          {
            "id": "food.hamburger_patties",
            "label": "Hamburger patties",
            "cell": "E50",
            "qty": "D50",
            "total": "F50"
          },
          {
            "id": "food.raviolis",
            "label": "Raviolis",
            "cell": "H50",
            "qty": "G50",
            "total": "I50"
          },
          {
            "id": "food.empanadas",
            "label": "Empanadas",
            "cell": "E51",
            "qty": "D51",
            "total": "F51"
          },
          {
            "id": "food.pierogis",
            "label": "Pierogis",
            "cell": "H51",
            "qty": "G51",
            "total": "I51"
          }
        ]
      },
      {
        "title": "Beverages",
        "lines": [
          {
            "id": "food.juice",
            "label": "Juice",
            "cell": "B53",
            "qty": "A53",
            "total": "C53",
            "note": true,
            "noteLabel": "Type",
            "text": "Juice -"
          },
          {
            "id": "food.tea_flavor",
            "label": "Tea",
            "cell": "E53",
            "qty": "D53",
            "total": "F53",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Tea - Flavor:"
          },
          {
            "id": "food.sports_drink_type_flavor",
            "label": "Sports Drink",
            "cell": "B54",
            "qty": "A54",
            "total": "C54",
            "note": true,
            "noteLabel": "Type/Flavor",
            "text": "Sports Drink - Type/Flavor:"
          },
          {
            "id": "food.soda_bottle",
            "label": "Bottle",
            "cell": "H54",
            "qty": "G54",
            "total": "I54",
            "group": "Soda"
          },
          {
            "id": "food.water_spring",
            "label": "Water spring",
            "cell": "B55",
            "qty": "A55",
            "total": "C55"
          },
          {
            "id": "food.coffee_filters_caffe",
            "label": "Caffe",
            "cell": "E55",
            "qty": "D55",
            "total": "F55",
            "group": "Coffee/Filters"
          },
          {
            "id": "food.soda_can",
            "label": "Can",
            "cell": "H55",
            "qty": "G55",
            "total": "I55",
            "group": "Soda"
          },
          {
            "id": "food.coffee_filters_decaf",
            "label": "Decaf",
            "cell": "E56",
            "qty": "D56",
            "total": "F56",
            "group": "Coffee/Filters"
          },
          {
            "id": "food.soda_flavor",
            "label": "Flavor",
            "cell": "H56",
            "qty": "G56",
            "total": "I56",
            "group": "Soda",
            "note": true,
            "noteLabel": "Which flavor",
            "text": "Flavor"
          }
        ]
      },
      {
        "title": "Meats",
        "lines": [
          {
            "id": "food.chorizo",
            "label": "Chorizo",
            "cell": "H58",
            "qty": "G58",
            "total": "I58"
          },
          {
            "id": "food.bacon_pork",
            "label": "Pork",
            "cell": "B59",
            "qty": "A59",
            "total": "C59",
            "group": "Bacon"
          },
          {
            "id": "food.ground_meat_pork",
            "label": "Pork",
            "cell": "E59",
            "qty": "D59",
            "total": "F59",
            "group": "Ground Meat"
          },
          {
            "id": "food.hot_dogs",
            "label": "Hot Dogs",
            "cell": "H59",
            "qty": "G59",
            "total": "I59"
          },
          {
            "id": "food.bacon_beef",
            "label": "Beef",
            "cell": "B60",
            "qty": "A60",
            "total": "C60",
            "group": "Bacon"
          },
          {
            "id": "food.ground_meat_beef",
            "label": "Beef",
            "cell": "E60",
            "qty": "D60",
            "total": "F60",
            "group": "Ground Meat"
          },
          {
            "id": "food.ham",
            "label": "Ham",
            "cell": "H60",
            "qty": "G60",
            "total": "I60"
          },
          {
            "id": "food.bacon_turkey",
            "label": "Turkey",
            "cell": "B61",
            "qty": "A61",
            "total": "C61",
            "group": "Bacon"
          },
          {
            "id": "food.ground_meat_turkey",
            "label": "Turkey",
            "cell": "E61",
            "qty": "D61",
            "total": "F61",
            "group": "Ground Meat"
          },
          {
            "id": "food.impossible_meat",
            "label": "Impossible Meat",
            "cell": "H61",
            "qty": "G61",
            "total": "I61"
          },
          {
            "id": "food.bacon_chicken",
            "label": "Chicken",
            "cell": "B62",
            "qty": "A62",
            "total": "C62",
            "group": "Bacon"
          },
          {
            "id": "food.ground_meat_chicken",
            "label": "Chicken",
            "cell": "E62",
            "qty": "D62",
            "total": "F62",
            "group": "Ground Meat"
          },
          {
            "id": "food.steak_t_bone",
            "label": "T-bone",
            "cell": "B64",
            "qty": "A64",
            "total": "C64",
            "group": "Steak"
          },
          {
            "id": "food.chicken_breast",
            "label": "Breast",
            "cell": "E64",
            "qty": "D64",
            "total": "F64",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_breast",
            "label": "Breast",
            "cell": "H64",
            "qty": "G64",
            "total": "I64",
            "group": "Turkey"
          },
          {
            "id": "food.steak_flank",
            "label": "Flank",
            "cell": "B65",
            "qty": "A65",
            "total": "C65",
            "group": "Steak"
          },
          {
            "id": "food.chicken_wings",
            "label": "Wings",
            "cell": "E65",
            "qty": "D65",
            "total": "F65",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_wings",
            "label": "Wings",
            "cell": "H65",
            "qty": "G65",
            "total": "I65",
            "group": "Turkey"
          },
          {
            "id": "food.steak_cubed",
            "label": "Cubed",
            "cell": "B66",
            "qty": "A66",
            "total": "C66",
            "group": "Steak"
          },
          {
            "id": "food.chicken_thighs",
            "label": "Thighs",
            "cell": "E66",
            "qty": "D66",
            "total": "F66",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_thighs",
            "label": "Thighs",
            "cell": "H66",
            "qty": "G66",
            "total": "I66",
            "group": "Turkey"
          },
          {
            "id": "food.steak_filet_mignon",
            "label": "Filet Mignon",
            "cell": "B67",
            "qty": "A67",
            "total": "C67",
            "group": "Steak"
          },
          {
            "id": "food.chicken_legs",
            "label": "Legs",
            "cell": "E67",
            "qty": "D67",
            "total": "F67",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_legs",
            "label": "Legs",
            "cell": "H67",
            "qty": "G67",
            "total": "I67",
            "group": "Turkey"
          },
          {
            "id": "food.steak_sirloin",
            "label": "Sirloin",
            "cell": "B68",
            "qty": "A68",
            "total": "C68",
            "group": "Steak"
          },
          {
            "id": "food.chicken_drumsticks",
            "label": "Drumsticks",
            "cell": "E68",
            "qty": "D68",
            "total": "F68",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_drumsticks",
            "label": "Drumsticks",
            "cell": "H68",
            "qty": "G68",
            "total": "I68",
            "group": "Turkey"
          },
          {
            "id": "food.steak_chuck_roast",
            "label": "Chuck roast",
            "cell": "B69",
            "qty": "A69",
            "total": "C69",
            "group": "Steak"
          },
          {
            "id": "food.chicken_tenderloin",
            "label": "Tenderloin",
            "cell": "E69",
            "qty": "D69",
            "total": "F69",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_tenderloin",
            "label": "Tenderloin",
            "cell": "H69",
            "qty": "G69",
            "total": "I69",
            "group": "Turkey"
          },
          {
            "id": "food.steak_rib_eye",
            "label": "Rib Eye",
            "cell": "B70",
            "qty": "A70",
            "total": "C70",
            "group": "Steak"
          },
          {
            "id": "food.chicken_whole",
            "label": "Whole",
            "cell": "E70",
            "qty": "D70",
            "total": "F70",
            "group": "Chicken"
          },
          {
            "id": "food.turkey_whole",
            "label": "Whole",
            "cell": "H70",
            "qty": "G70",
            "total": "I70",
            "group": "Turkey"
          },
          {
            "id": "food.steak_shaved",
            "label": "Shaved",
            "cell": "B71",
            "qty": "A71",
            "total": "C71",
            "group": "Steak"
          },
          {
            "id": "food.steak_skirt",
            "label": "Skirt",
            "cell": "B72",
            "qty": "A72",
            "total": "C72",
            "group": "Steak"
          },
          {
            "id": "food.sausages_pork",
            "label": "Pork",
            "cell": "E72",
            "qty": "D72",
            "total": "F72",
            "group": "Sausages"
          },
          {
            "id": "food.sausages_turkey",
            "label": "Turkey",
            "cell": "H72",
            "qty": "G72",
            "total": "I72",
            "group": "Sausages"
          },
          {
            "id": "food.steak_eye_of_round",
            "label": "Eye of Round",
            "cell": "B73",
            "qty": "A73",
            "total": "C73",
            "group": "Steak"
          },
          {
            "id": "food.sausages_beef",
            "label": "Beef",
            "cell": "E73",
            "qty": "D73",
            "total": "F73",
            "group": "Sausages"
          },
          {
            "id": "food.sausages_chicken",
            "label": "Chicken",
            "cell": "H73",
            "qty": "G73",
            "total": "I73",
            "group": "Sausages"
          },
          {
            "id": "food.steak_hanger",
            "label": "Hanger",
            "cell": "B74",
            "qty": "A74",
            "total": "C74",
            "group": "Steak"
          },
          {
            "id": "food.sausages_sweet",
            "label": "Sweet",
            "cell": "E74",
            "qty": "D74",
            "total": "F74",
            "group": "Sausages"
          },
          {
            "id": "food.sausages_hot",
            "label": "Hot",
            "cell": "H74",
            "qty": "G74",
            "total": "I74",
            "group": "Sausages"
          },
          {
            "id": "food.steak_ribs",
            "label": "Ribs",
            "cell": "B75",
            "qty": "A75",
            "total": "C75",
            "group": "Steak"
          },
          {
            "id": "food.sausages_vienna",
            "label": "Vienna",
            "cell": "E75",
            "qty": "D75",
            "total": "F75",
            "group": "Sausages"
          },
          {
            "id": "food.sausages_breakfast",
            "label": "Breakfast",
            "cell": "H75",
            "qty": "G75",
            "total": "I75",
            "group": "Sausages"
          },
          {
            "id": "food.pork_chops",
            "label": "Chops",
            "cell": "E77",
            "qty": "D77",
            "total": "F77",
            "group": "Pork"
          },
          {
            "id": "food.pork_ribs",
            "label": "Ribs",
            "cell": "H77",
            "qty": "G77",
            "total": "I77",
            "group": "Pork"
          }
        ]
      },
      {
        "title": "Spices & Herbs",
        "lines": [
          {
            "id": "food.basil",
            "label": "Basil",
            "cell": "B79",
            "qty": "A79",
            "total": "C79"
          },
          {
            "id": "food.black_pepper",
            "label": "Black Pepper",
            "cell": "E79",
            "qty": "D79",
            "total": "F79"
          },
          {
            "id": "food.cilantro",
            "label": "Cilantro",
            "cell": "H79",
            "qty": "G79",
            "total": "I79"
          },
          {
            "id": "food.cinnamon",
            "label": "Cinnamon",
            "cell": "B80",
            "qty": "A80",
            "total": "C80"
          },
          {
            "id": "food.garlic_powder",
            "label": "Garlic Powder",
            "cell": "E80",
            "qty": "D80",
            "total": "F80"
          },
          {
            "id": "food.onion_powder",
            "label": "Onion Powder",
            "cell": "H80",
            "qty": "G80",
            "total": "I80"
          },
          {
            "id": "food.oregano",
            "label": "Oregano",
            "cell": "B81",
            "qty": "A81",
            "total": "C81"
          },
          {
            "id": "food.paprika",
            "label": "Paprika",
            "cell": "E81",
            "qty": "D81",
            "total": "F81"
          },
          {
            "id": "food.red_pepper",
            "label": "Red Pepper",
            "cell": "H81",
            "qty": "G81",
            "total": "I81"
          },
          {
            "id": "food.salt",
            "label": "Salt",
            "cell": "B82",
            "qty": "A82",
            "total": "C82"
          },
          {
            "id": "food.thyme",
            "label": "Thyme",
            "cell": "E82",
            "qty": "D82",
            "total": "F82"
          },
          {
            "id": "food.adobo",
            "label": "Adobo",
            "cell": "H82",
            "qty": "G82",
            "total": "I82"
          },
          {
            "id": "food.salt_substitute",
            "label": "Salt Substitute",
            "cell": "B83",
            "qty": "A83",
            "total": "C83"
          },
          {
            "id": "food.seasoning_salt",
            "label": "Seasoning Salt",
            "cell": "E83",
            "qty": "D83",
            "total": "F83"
          },
          {
            "id": "food.ginger",
            "label": "Ginger",
            "cell": "H83",
            "qty": "G83",
            "total": "I83"
          },
          {
            "id": "food.italian_seasoning",
            "label": "Italian Seasoning",
            "cell": "B84",
            "qty": "A84",
            "total": "C84"
          },
          {
            "id": "food.cumin",
            "label": "Cumin",
            "cell": "E84",
            "qty": "D84",
            "total": "F84"
          },
          {
            "id": "food.bay_leaves",
            "label": "Bay leaves",
            "cell": "H84",
            "qty": "G84",
            "total": "I84"
          },
          {
            "id": "food.parsley",
            "label": "Parsley",
            "cell": "B85",
            "qty": "A85",
            "total": "C85"
          },
          {
            "id": "food.mrs_dash",
            "label": "Mrs. Dash",
            "cell": "E85",
            "qty": "D85",
            "total": "F85"
          },
          {
            "id": "food.curry",
            "label": "Curry",
            "cell": "H85",
            "qty": "G85",
            "total": "I85"
          }
        ]
      },
      {
        "title": "Baked Goods",
        "lines": [
          {
            "id": "food.bagels",
            "label": "Bagels",
            "cell": "B87",
            "qty": "A87",
            "total": "C87"
          },
          {
            "id": "food.pie",
            "label": "Pie",
            "cell": "E87",
            "qty": "D87",
            "total": "F87"
          },
          {
            "id": "food.blueberry_muffins",
            "label": "Blueberry Muffins",
            "cell": "H87",
            "qty": "G87",
            "total": "I87"
          },
          {
            "id": "food.pita_bread",
            "label": "Pita Bread",
            "cell": "B88",
            "qty": "A88",
            "total": "C88"
          },
          {
            "id": "food.buns_rolls",
            "label": "Buns/Rolls",
            "cell": "E88",
            "qty": "D88",
            "total": "F88"
          },
          {
            "id": "food.taco_shells_hard_soft",
            "label": "Taco Shells",
            "cell": "H88",
            "qty": "G88",
            "total": "I88",
            "note": true,
            "noteLabel": "Hard/Soft",
            "text": "Taco Shells: Hard/Soft"
          },
          {
            "id": "food.tortillas",
            "label": "Tortillas",
            "cell": "B89",
            "qty": "A89",
            "total": "C89"
          }
        ]
      },
      {
        "title": "Baking",
        "lines": [
          {
            "id": "food.baking_powder_soda",
            "label": "Baking Powder/Soda",
            "cell": "B91",
            "qty": "A91",
            "total": "C91"
          },
          {
            "id": "food.flour",
            "label": "Flour",
            "cell": "E91",
            "qty": "D91",
            "total": "F91"
          },
          {
            "id": "food.icing_frosting_flavor",
            "label": "Icing/Frosting",
            "cell": "B92",
            "qty": "A92",
            "total": "C92",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Icing/Frosting: Flavor"
          },
          {
            "id": "food.yeast",
            "label": "Yeast",
            "cell": "E92",
            "qty": "D92",
            "total": "F92"
          },
          {
            "id": "food.extract_orange",
            "label": "Orange",
            "cell": "H92",
            "qty": "G92",
            "total": "I92",
            "group": "Extract"
          },
          {
            "id": "food.sugar_sugar_substitute",
            "label": "Sugar/Sugar Substitute",
            "cell": "B93",
            "qty": "A93",
            "total": "C93"
          },
          {
            "id": "food.extract_vanilla",
            "label": "Vanilla",
            "cell": "H93",
            "qty": "G93",
            "total": "I93",
            "group": "Extract"
          },
          {
            "id": "food.cake_brownie_mix",
            "label": "Cake/Brownie Mix",
            "cell": "B94",
            "qty": "A94",
            "total": "C94"
          },
          {
            "id": "food.extract_almond",
            "label": "Almond",
            "cell": "H94",
            "qty": "G94",
            "total": "I94",
            "group": "Extract"
          },
          {
            "id": "food.shortening",
            "label": "Shortening",
            "cell": "B95",
            "qty": "A95",
            "total": "C95"
          },
          {
            "id": "food.extract_anise",
            "label": "Anise",
            "cell": "H95",
            "qty": "G95",
            "total": "I95",
            "group": "Extract"
          },
          {
            "id": "food.bread_crumbs",
            "label": "Bread Crumbs",
            "cell": "B96",
            "qty": "A96",
            "total": "C96"
          },
          {
            "id": "food.extract_licorice",
            "label": "Licorice",
            "cell": "H96",
            "qty": "G96",
            "total": "I96",
            "group": "Extract"
          }
        ]
      },
      {
        "title": "Bread",
        "lines": [
          {
            "id": "food.bread",
            "label": "Bread",
            "cell": "B98",
            "qty": "A98",
            "total": "C98"
          },
          {
            "id": "food.box_of_crackers_type",
            "label": "Box of Crackers",
            "cell": "E98",
            "qty": "D98",
            "total": "F98",
            "note": true,
            "noteLabel": "Type",
            "text": "Box of Crackers: Type"
          },
          {
            "id": "food.hot_dog_buns",
            "label": "Hot Dog Buns",
            "cell": "B99",
            "qty": "A99",
            "total": "C99"
          },
          {
            "id": "food.hamburger_buns",
            "label": "Hamburger Buns",
            "cell": "E99",
            "qty": "D99",
            "total": "F99"
          }
        ]
      },
      {
        "title": "Various Groceries",
        "lines": [
          {
            "id": "food.cereal",
            "label": "Cereal",
            "cell": "B101",
            "qty": "A101",
            "total": "C101",
            "note": true,
            "noteLabel": "Type",
            "text": "1 Cereal:"
          },
          {
            "id": "food.cooking_wine",
            "label": "Cooking Wine",
            "cell": "E101",
            "qty": "D101",
            "total": "F101"
          },
          {
            "id": "food.pancake_mix",
            "label": "Pancake Mix",
            "cell": "H101",
            "qty": "G101",
            "total": "I101"
          },
          {
            "id": "food.vinegar",
            "label": "Vinegar",
            "cell": "B102",
            "qty": "A102",
            "total": "C102"
          },
          {
            "id": "food.rice",
            "label": "Rice",
            "cell": "E102",
            "qty": "D102",
            "total": "F102"
          },
          {
            "id": "food.broth",
            "label": "Broth",
            "cell": "H102",
            "qty": "G102",
            "total": "I102"
          },
          {
            "id": "food.olives",
            "label": "Olives",
            "cell": "B103",
            "qty": "A103",
            "total": "C103"
          },
          {
            "id": "food.lime_juice",
            "label": "Lime Juice",
            "cell": "E103",
            "qty": "D103",
            "total": "F103"
          },
          {
            "id": "food.lemon_juice",
            "label": "Lemon Juice",
            "cell": "H103",
            "qty": "G103",
            "total": "I103"
          },
          {
            "id": "food.peanut_butter",
            "label": "Peanut Butter",
            "cell": "B104",
            "qty": "A104",
            "total": "C104"
          },
          {
            "id": "food.canned_beans_type",
            "label": "Canned Beans",
            "cell": "E104",
            "qty": "D104",
            "total": "F104",
            "note": true,
            "noteLabel": "Type",
            "text": "Canned Beans: Type"
          },
          {
            "id": "food.soup",
            "label": "Soup",
            "cell": "H104",
            "qty": "G104",
            "total": "I104",
            "note": true,
            "noteLabel": "Type",
            "text": "Soup:"
          },
          {
            "id": "food.applesauce",
            "label": "Applesauce",
            "cell": "B105",
            "qty": "A105",
            "total": "C105"
          },
          {
            "id": "food.canned_fruit",
            "label": "Canned Fruit",
            "cell": "E105",
            "qty": "D105",
            "total": "F105",
            "note": true,
            "noteLabel": "Type",
            "text": "Canned Fruit:"
          },
          {
            "id": "food.oatmeal",
            "label": "Oatmeal",
            "cell": "H105",
            "qty": "G105",
            "total": "I105"
          },
          {
            "id": "food.tuna",
            "label": "Tuna",
            "cell": "B106",
            "qty": "A106",
            "total": "C106"
          },
          {
            "id": "food.instant_potatoes",
            "label": "Instant Potatoes",
            "cell": "E106",
            "qty": "D106",
            "total": "F106"
          },
          {
            "id": "food.chili",
            "label": "Chili",
            "cell": "B107",
            "qty": "A107",
            "total": "C107"
          },
          {
            "id": "food.mac_cheese",
            "label": "Mac & Cheese",
            "cell": "E107",
            "qty": "D107",
            "total": "F107"
          },
          {
            "id": "food.pasta_lasagna",
            "label": "Lasagna",
            "cell": "B109",
            "qty": "A109",
            "total": "C109",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_fettucine",
            "label": "Fettucine",
            "cell": "E109",
            "qty": "D109",
            "total": "F109",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_penne",
            "label": "Penne",
            "cell": "H109",
            "qty": "G109",
            "total": "I109",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_spaghetti",
            "label": "Spaghetti",
            "cell": "B110",
            "qty": "A110",
            "total": "C110",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_bowtie_farfalle",
            "label": "Bowtie/Farfalle",
            "cell": "E110",
            "qty": "D110",
            "total": "F110",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_fussili",
            "label": "Fussili",
            "cell": "H110",
            "qty": "G110",
            "total": "I110",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_rigatoni",
            "label": "Rigatoni",
            "cell": "B111",
            "qty": "A111",
            "total": "C111",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_linguine",
            "label": "Linguine",
            "cell": "E111",
            "qty": "D111",
            "total": "F111",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_angel_hair",
            "label": "Angel Hair",
            "cell": "H111",
            "qty": "G111",
            "total": "I111",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_orzo",
            "label": "Orzo",
            "cell": "B112",
            "qty": "A112",
            "total": "C112",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_elbow",
            "label": "Elbow",
            "cell": "E112",
            "qty": "D112",
            "total": "F112",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_ziti",
            "label": "Ziti",
            "cell": "H112",
            "qty": "G112",
            "total": "I112",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_gnocchi",
            "label": "Gnocchi",
            "cell": "B113",
            "qty": "A113",
            "total": "C113",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_shells",
            "label": "Shells",
            "cell": "E113",
            "qty": "D113",
            "total": "F113",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_ravioli",
            "label": "Ravioli",
            "cell": "H113",
            "qty": "G113",
            "total": "I113",
            "group": "Pasta"
          },
          {
            "id": "food.pasta_tortellini",
            "label": "Tortellini",
            "cell": "B114",
            "qty": "A114",
            "total": "C114",
            "group": "Pasta"
          },
          {
            "id": "food.sauce_meat",
            "label": "Meat",
            "cell": "B116",
            "qty": "A116",
            "total": "C116",
            "group": "Sauce"
          },
          {
            "id": "food.sauce_tomato",
            "label": "Tomato",
            "cell": "E116",
            "qty": "D116",
            "total": "F116",
            "group": "Sauce"
          },
          {
            "id": "food.sauce_alfredo",
            "label": "Alfredo",
            "cell": "H116",
            "qty": "G116",
            "total": "I116",
            "group": "Sauce"
          },
          {
            "id": "food.sauce_marinara",
            "label": "Marinara",
            "cell": "B117",
            "qty": "A117",
            "total": "C117",
            "group": "Sauce"
          },
          {
            "id": "food.sauce_vodka",
            "label": "Vodka",
            "cell": "E117",
            "qty": "D117",
            "total": "F117",
            "group": "Sauce"
          },
          {
            "id": "food.sauce_other",
            "label": "Other",
            "cell": "H117",
            "qty": "G117",
            "total": "I117",
            "group": "Sauce",
            "note": true,
            "noteLabel": "Type",
            "text": "Other:"
          },
          {
            "id": "food.oil_vegetable",
            "label": "Vegetable",
            "cell": "B119",
            "qty": "A119",
            "total": "C119",
            "group": "Oil"
          },
          {
            "id": "food.oil_olive",
            "label": "Olive",
            "cell": "E119",
            "qty": "D119",
            "total": "F119",
            "group": "Oil"
          },
          {
            "id": "food.oil_peanut",
            "label": "Peanut",
            "cell": "H119",
            "qty": "G119",
            "total": "I119",
            "group": "Oil"
          },
          {
            "id": "food.oil_canola",
            "label": "Canola",
            "cell": "B120",
            "qty": "A120",
            "total": "C120",
            "group": "Oil"
          },
          {
            "id": "food.oil_evoo",
            "label": "EVOO",
            "cell": "E120",
            "qty": "D120",
            "total": "F120",
            "group": "Oil"
          },
          {
            "id": "food.oil_avocado",
            "label": "Avocado",
            "cell": "H120",
            "qty": "G120",
            "total": "I120",
            "group": "Oil"
          }
        ]
      },
      {
        "title": "Snacks",
        "lines": [
          {
            "id": "food.nuts_seeds",
            "label": "Nuts/Seeds",
            "cell": "B122",
            "qty": "A122",
            "total": "C122"
          },
          {
            "id": "food.cookies_flavor",
            "label": "Cookies",
            "cell": "E122",
            "qty": "D122",
            "total": "F122",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Cookies - Flavor:"
          },
          {
            "id": "food.potato_chips",
            "label": "Potato Chips",
            "cell": "H122",
            "qty": "G122",
            "total": "I122",
            "note": true,
            "noteLabel": "Type",
            "text": "Potato Chips -"
          },
          {
            "id": "food.chip_dip",
            "label": "Chip Dip",
            "cell": "B123",
            "qty": "A123",
            "total": "C123"
          },
          {
            "id": "food.jell_o_flavor",
            "label": "Jell-O",
            "cell": "E123",
            "qty": "D123",
            "total": "F123",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Jell-O - Flavor:"
          },
          {
            "id": "food.granola_bars",
            "label": "Granola bars",
            "cell": "B124",
            "qty": "A124",
            "total": "C124"
          },
          {
            "id": "food.pudding_flavor",
            "label": "Pudding",
            "cell": "E124",
            "qty": "D124",
            "total": "F124",
            "note": true,
            "noteLabel": "Flavor",
            "text": "Pudding - Flavor:"
          },
          {
            "id": "food.pretzels",
            "label": "Pretzels",
            "cell": "B125",
            "qty": "A125",
            "total": "C125"
          },
          {
            "id": "food.doritos",
            "label": "Doritos",
            "cell": "B126",
            "qty": "A126",
            "total": "C126"
          },
          {
            "id": "food.popcorn",
            "label": "Popcorn",
            "cell": "B127",
            "qty": "A127",
            "total": "C127"
          }
        ]
      },
      {
        "title": "Other Food Items",
        "lines": [
          {
            "id": "food.other1",
            "cell": "B129",
            "qty": "A129",
            "total": "I129",
            "multi": true,
            "free": true
          }
        ]
      },
      {
        "title": "Additional Food Choices",
        "lines": [
          {
            "id": "food.quaker_avena",
            "label": "Quaker Avena",
            "cell": "B134",
            "qty": "A134",
            "total": "C134"
          },
          {
            "id": "food.ghee",
            "label": "Ghee",
            "cell": "E134",
            "qty": "D134",
            "total": "F134"
          },
          {
            "id": "food.queso_de_freir",
            "label": "Queso de Freir",
            "cell": "H134",
            "qty": "G134",
            "total": "I134"
          },
          {
            "id": "food.paneer",
            "label": "Paneer",
            "cell": "B135",
            "qty": "A135",
            "total": "C135"
          },
          {
            "id": "food.galletas_por_soda",
            "label": "Galletas por soda",
            "cell": "E135",
            "qty": "D135",
            "total": "F135"
          },
          {
            "id": "food.fansi",
            "label": "Fansi",
            "cell": "H135",
            "qty": "G135",
            "total": "I135"
          },
          {
            "id": "food.caf_bustelo",
            "label": "Caf\u00e9 Bustelo",
            "cell": "B136",
            "qty": "A136",
            "total": "C136"
          },
          {
            "id": "food.desi_okra",
            "label": "Desi Okra",
            "cell": "E136",
            "qty": "D136",
            "total": "F136"
          },
          {
            "id": "food.yucca",
            "label": "Yucca",
            "cell": "H136",
            "qty": "G136",
            "total": "I136"
          },
          {
            "id": "food.yautia",
            "label": "Yautia",
            "cell": "B137",
            "qty": "A137",
            "total": "C137"
          },
          {
            "id": "food.methi",
            "label": "Methi",
            "cell": "E137",
            "qty": "D137",
            "total": "F137"
          },
          {
            "id": "food.madris_curry",
            "label": "Madris Curry",
            "cell": "H137",
            "qty": "G137",
            "total": "I137"
          },
          {
            "id": "food.bacalao",
            "label": "Bacalao",
            "cell": "B138",
            "qty": "A138",
            "total": "C138"
          },
          {
            "id": "food.dhana",
            "label": "Dhana",
            "cell": "E138",
            "qty": "D138",
            "total": "F138"
          },
          {
            "id": "food.coriander",
            "label": "Coriander",
            "cell": "H138",
            "qty": "G138",
            "total": "I138"
          },
          {
            "id": "food.calabaza",
            "label": "Calabaza",
            "cell": "B139",
            "qty": "A139",
            "total": "C139"
          },
          {
            "id": "food.mustard_seed",
            "label": "Mustard Seed",
            "cell": "E139",
            "qty": "D139",
            "total": "F139"
          },
          {
            "id": "food.sesame_seeds",
            "label": "Sesame Seeds",
            "cell": "H139",
            "qty": "G139",
            "total": "I139"
          },
          {
            "id": "food.malanga",
            "label": "Malanga",
            "cell": "B140",
            "qty": "A140",
            "total": "C140"
          },
          {
            "id": "food.pig_s_feet",
            "label": "Pig\u2019s Feet",
            "cell": "E140",
            "qty": "D140",
            "total": "F140"
          },
          {
            "id": "food.sofrito",
            "label": "Sofrito",
            "cell": "H140",
            "qty": "G140",
            "total": "I140"
          },
          {
            "id": "food.chayote",
            "label": "Chayote",
            "cell": "B141",
            "qty": "A141",
            "total": "C141"
          },
          {
            "id": "food.pico_rice",
            "label": "Pico Rice",
            "cell": "E141",
            "qty": "D141",
            "total": "F141"
          },
          {
            "id": "food.sazon",
            "label": "Sazon",
            "cell": "H141",
            "qty": "G141",
            "total": "I141"
          },
          {
            "id": "food.chicken_gizzards",
            "label": "Chicken Gizzards",
            "cell": "B142",
            "qty": "A142",
            "total": "C142"
          },
          {
            "id": "food.pigeon_pease",
            "label": "Pigeon Pease",
            "cell": "E142",
            "qty": "D142",
            "total": "F142"
          },
          {
            "id": "food.mojo_criollo",
            "label": "Mojo Criollo",
            "cell": "H142",
            "qty": "G142",
            "total": "I142"
          },
          {
            "id": "food.bouillon_chicken_beef_ham",
            "label": "Bouillon",
            "cell": "B143",
            "qty": "A143",
            "total": "C143",
            "note": true,
            "noteLabel": "Chicken/beef/ham",
            "text": "Bouillon: Chicken/beef/ham"
          },
          {
            "id": "food.mamra",
            "label": "Mamra",
            "cell": "E143",
            "qty": "D143",
            "total": "F143"
          },
          {
            "id": "food.tandoori",
            "label": "Tandoori",
            "cell": "H143",
            "qty": "G143",
            "total": "I143"
          },
          {
            "id": "food.recao_leaf",
            "label": "Recao Leaf",
            "cell": "B144",
            "qty": "A144",
            "total": "C144"
          },
          {
            "id": "food.dhanadal",
            "label": "Dhanadal",
            "cell": "E144",
            "qty": "D144",
            "total": "F144"
          },
          {
            "id": "food.agro_corn",
            "label": "Agro Corn",
            "cell": "H144",
            "qty": "G144",
            "total": "I144"
          },
          {
            "id": "food.noga_dahi_whole",
            "label": "Noga Dahi Whole",
            "cell": "B145",
            "qty": "A145",
            "total": "C145"
          },
          {
            "id": "food.moong_whole",
            "label": "Moong Whole",
            "cell": "E145",
            "qty": "D145",
            "total": "F145"
          },
          {
            "id": "food.chandan_agar",
            "label": "Chandan Agar",
            "cell": "H145",
            "qty": "G145",
            "total": "I145"
          },
          {
            "id": "food.poha_thin",
            "label": "Poha Thin",
            "cell": "B146",
            "qty": "A146",
            "total": "C146"
          },
          {
            "id": "food.moong_dal",
            "label": "Moong Dal",
            "cell": "E146",
            "qty": "D146",
            "total": "F146"
          },
          {
            "id": "food.poha_thick",
            "label": "Poha Thick",
            "cell": "H146",
            "qty": "G146",
            "total": "I146"
          },
          {
            "id": "food.rajara_flour",
            "label": "Rajara Flour",
            "cell": "B147",
            "qty": "A147",
            "total": "C147"
          },
          {
            "id": "food.kolhapuri",
            "label": "Kolhapuri",
            "cell": "E147",
            "qty": "D147",
            "total": "F147"
          }
        ]
      }
    ]
  },
  {
    "id": "pantry",
    "title": "Pantry",
    "sheet": "xl/worksheets/sheet4.xml",
    "totalCell": "F27",
    "sections": [
      {
        "title": "Kitchen",
        "lines": [
          {
            "id": "pantry.aluminum_foil",
            "label": "Aluminum foil",
            "cell": "B2",
            "qty": "A2",
            "total": "C2"
          },
          {
            "id": "pantry.napkins",
            "label": "Napkins",
            "cell": "E2",
            "qty": "D2",
            "total": "F2"
          },
          {
            "id": "pantry.paper_towels",
            "label": "Paper Towels",
            "cell": "B3",
            "qty": "A3",
            "total": "C3"
          },
          {
            "id": "pantry.non_stick_spray",
            "label": "Non-stick Spray",
            "cell": "E3",
            "qty": "D3",
            "total": "F3"
          },
          {
            "id": "pantry.plastic_wrap",
            "label": "Plastic Wrap",
            "cell": "B4",
            "qty": "A4",
            "total": "C4"
          },
          {
            "id": "pantry.sandwich_bags",
            "label": "Sandwich Bags",
            "cell": "E4",
            "qty": "D4",
            "total": "F4"
          },
          {
            "id": "pantry.parchment_paper",
            "label": "Parchment Paper",
            "cell": "B5",
            "qty": "A5",
            "total": "C5"
          },
          {
            "id": "pantry.gallon_zip_lock_bags",
            "label": "Gallon zip lock bags",
            "cell": "E5",
            "qty": "D5",
            "total": "F5"
          }
        ]
      },
      {
        "title": "Cleaning Supplies",
        "lines": [
          {
            "id": "pantry.air_freshener",
            "label": "Air Freshener",
            "cell": "B7",
            "qty": "A7",
            "total": "C7"
          },
          {
            "id": "pantry.bathroom_cleaner",
            "label": "Bathroom Cleaner",
            "cell": "E7",
            "qty": "D7",
            "total": "F7"
          },
          {
            "id": "pantry.bleach",
            "label": "Bleach",
            "cell": "B8",
            "qty": "A8",
            "total": "C8"
          },
          {
            "id": "pantry.laundry_detergent",
            "label": "Laundry Detergent",
            "cell": "E8",
            "qty": "D8",
            "total": "F8"
          },
          {
            "id": "pantry.dish_washer_soap",
            "label": "Dish / Washer Soap",
            "cell": "B9",
            "qty": "A9",
            "total": "C9"
          },
          {
            "id": "pantry.garbage_bags",
            "label": "Garbage Bags",
            "cell": "E9",
            "qty": "D9",
            "total": "F9"
          },
          {
            "id": "pantry.clorox_lysol_wipes",
            "label": "Clorox / Lysol Wipes",
            "cell": "B10",
            "qty": "A10",
            "total": "C10"
          },
          {
            "id": "pantry.sponges",
            "label": "Sponges",
            "cell": "E10",
            "qty": "D10",
            "total": "F10"
          },
          {
            "id": "pantry.glass_cleaner",
            "label": "Glass Cleaner",
            "cell": "B11",
            "qty": "A11",
            "total": "C11"
          },
          {
            "id": "pantry.broom_dustpan",
            "label": "Broom/Dustpan",
            "cell": "E11",
            "qty": "D11",
            "total": "F11"
          },
          {
            "id": "pantry.toilet_bowl_cleaner",
            "label": "Toilet Bowl Cleaner",
            "cell": "B12",
            "qty": "A12",
            "total": "C12"
          },
          {
            "id": "pantry.toilet_bowl_brush",
            "label": "Toilet Bowl Brush",
            "cell": "E12",
            "qty": "D12",
            "total": "F12"
          },
          {
            "id": "pantry.mop_bucket_or_push_mop",
            "label": "Mop & Bucket OR Push Mop",
            "cell": "B13",
            "qty": "A13",
            "total": "C13",
            "note": true,
            "noteLabel": "Which one",
            "text": "Mop & Bucket OR Push Mop"
          },
          {
            "id": "pantry.other_cleaner",
            "label": "Other Cleaner",
            "cell": "B14",
            "qty": "A14",
            "total": "C14",
            "note": true,
            "noteLabel": "Type",
            "text": "Other Cleaner:"
          }
        ]
      },
      {
        "title": "Office Supplies",
        "lines": [
          {
            "id": "pantry.pens",
            "label": "Pens",
            "cell": "B16",
            "qty": "A16",
            "total": "C16"
          },
          {
            "id": "pantry.pencils",
            "label": "Pencils",
            "cell": "E16",
            "qty": "D16",
            "total": "F16"
          },
          {
            "id": "pantry.calendar",
            "label": "Calendar",
            "cell": "B17",
            "qty": "A17",
            "total": "C17"
          },
          {
            "id": "pantry.planner",
            "label": "Planner",
            "cell": "E17",
            "qty": "D17",
            "total": "F17"
          },
          {
            "id": "pantry.glue",
            "label": "Glue",
            "cell": "B18",
            "qty": "A18",
            "total": "C18"
          },
          {
            "id": "pantry.tape",
            "label": "Tape",
            "cell": "E18",
            "qty": "D18",
            "total": "F18"
          },
          {
            "id": "pantry.notepad",
            "label": "Notepad",
            "cell": "B19",
            "qty": "A19",
            "total": "C19"
          },
          {
            "id": "pantry.envelopes",
            "label": "Envelopes",
            "cell": "E19",
            "qty": "D19",
            "total": "F19"
          }
        ]
      },
      {
        "title": "Extras",
        "lines": [
          {
            "id": "pantry.batteries",
            "label": "Batteries",
            "cell": "B21",
            "qty": "A21",
            "total": "C21"
          },
          {
            "id": "pantry.light_bulbs",
            "label": "Light bulbs",
            "cell": "E21",
            "qty": "D21",
            "total": "F21"
          },
          {
            "id": "pantry.extension_cord",
            "label": "Extension Cord",
            "cell": "B22",
            "qty": "A22",
            "total": "C22"
          },
          {
            "id": "pantry.bandaids",
            "label": "Bandaids",
            "cell": "E22",
            "qty": "D22",
            "total": "F22"
          },
          {
            "id": "pantry.flashlight",
            "label": "Flashlight",
            "cell": "B23",
            "qty": "A23",
            "total": "C23"
          }
        ]
      },
      {
        "title": "Other Pantry Items",
        "lines": [
          {
            "id": "pantry.other1",
            "cell": "A25",
            "total": "F25",
            "free": true
          },
          {
            "id": "pantry.other2",
            "cell": "A26",
            "total": "F26",
            "free": true
          }
        ]
      }
    ]
  },
  {
    "id": "hygiene",
    "title": "Hygiene",
    "sheet": "xl/worksheets/sheet4.xml",
    "totalCell": "Q12",
    "sections": [
      {
        "title": "Personal Hygiene",
        "lines": [
          {
            "id": "hygiene.razor_shaving_cream_electric_razor",
            "label": "Razor/Shaving Cream / Electric Razor",
            "cell": "J2",
            "qty": "I2",
            "total": "K2"
          },
          {
            "id": "hygiene.feminine_products",
            "label": "Feminine Products",
            "cell": "M2",
            "qty": "L2",
            "total": "N2"
          },
          {
            "id": "hygiene.toilet_paper",
            "label": "Toilet Paper",
            "cell": "P2",
            "qty": "O2",
            "total": "Q2"
          },
          {
            "id": "hygiene.first_aid_supplies",
            "label": "First Aid Supplies",
            "cell": "J3",
            "qty": "I3",
            "total": "K3"
          },
          {
            "id": "hygiene.hairspray_gel_mousse",
            "label": "Hairspray/Gel/Mousse",
            "cell": "M3",
            "qty": "L3",
            "total": "N3"
          },
          {
            "id": "hygiene.tissues",
            "label": "Tissues",
            "cell": "P3",
            "qty": "O3",
            "total": "Q3"
          },
          {
            "id": "hygiene.lip_balm",
            "label": "Lip Balm",
            "cell": "J4",
            "qty": "I4",
            "total": "K4"
          },
          {
            "id": "hygiene.cotton_swab_balls",
            "label": "Cotton Swab/Balls",
            "cell": "M4",
            "qty": "L4",
            "total": "N4"
          },
          {
            "id": "hygiene.floss",
            "label": "Floss",
            "cell": "P4",
            "qty": "O4",
            "total": "Q4"
          },
          {
            "id": "hygiene.shampoo",
            "label": "Shampoo",
            "cell": "J5",
            "qty": "I5",
            "total": "K5"
          },
          {
            "id": "hygiene.lotion",
            "label": "Lotion",
            "cell": "M5",
            "qty": "L5",
            "total": "N5"
          },
          {
            "id": "hygiene.toothbrush",
            "label": "Toothbrush",
            "cell": "P5",
            "qty": "O5",
            "total": "Q5"
          },
          {
            "id": "hygiene.conditioner",
            "label": "Conditioner",
            "cell": "J6",
            "qty": "I6",
            "total": "K6"
          },
          {
            "id": "hygiene.deodorant",
            "label": "Deodorant",
            "cell": "M6",
            "qty": "L6",
            "total": "N6"
          },
          {
            "id": "hygiene.toothpaste",
            "label": "Toothpaste",
            "cell": "P6",
            "qty": "O6",
            "total": "Q6"
          },
          {
            "id": "hygiene.body_wash_bar_soap",
            "label": "Body Wash/Bar Soap",
            "cell": "J7",
            "qty": "I7",
            "total": "K7"
          },
          {
            "id": "hygiene.hand_soap",
            "label": "Hand Soap",
            "cell": "M7",
            "qty": "L7",
            "total": "N7"
          },
          {
            "id": "hygiene.mouthwash",
            "label": "Mouthwash",
            "cell": "P7",
            "qty": "O7",
            "total": "Q7"
          },
          {
            "id": "hygiene.wipes_incontinence",
            "label": "Wipes (incontinence)",
            "cell": "J8",
            "qty": "I8",
            "total": "K8"
          }
        ]
      },
      {
        "title": "Other Personal Hygiene",
        "lines": [
          {
            "id": "hygiene.other1",
            "cell": "J10",
            "qty": "I10",
            "total": "Q10",
            "free": true
          },
          {
            "id": "hygiene.other2",
            "cell": "J11",
            "qty": "I11",
            "total": "Q11",
            "free": true
          }
        ]
      }
    ]
  },
  {
    "id": "clothing",
    "title": "Clothing",
    "sheet": "xl/worksheets/sheet4.xml",
    "totalCell": "W17",
    "sections": [
      {
        "title": "Clothing",
        "lines": [
          {
            "id": "clothing.underwear",
            "label": "Underwear",
            "cell": "W2",
            "qty": "U2",
            "total": "V2",
            "size": "T2"
          },
          {
            "id": "clothing.bras_front_back",
            "label": "Bras",
            "cell": "W3",
            "qty": "U3",
            "total": "V3",
            "size": "T3",
            "note": true,
            "noteLabel": "Front/Back",
            "text": "Bras (Front/Back)"
          },
          {
            "id": "clothing.socks_compression_socks_ordered_through_",
            "label": "Socks (Compression socks ordered through DME)",
            "cell": "W4",
            "qty": "U4",
            "total": "V4",
            "size": "T4"
          },
          {
            "id": "clothing.white_t_shirt_cami",
            "label": "White T Shirt/Cami",
            "cell": "W5",
            "qty": "U5",
            "total": "V5",
            "size": "T5"
          },
          {
            "id": "clothing.sweatpants",
            "label": "Sweatpants",
            "cell": "W6",
            "qty": "U6",
            "total": "V6",
            "size": "T6"
          }
        ]
      },
      {
        "title": "Other Clothing",
        "lines": [
          {
            "id": "clothing.other1",
            "cell": "W8",
            "qty": "U8",
            "total": "V8",
            "size": "T8",
            "free": true
          },
          {
            "id": "clothing.other2",
            "cell": "W9",
            "qty": "U9",
            "total": "V9",
            "size": "T9",
            "free": true
          },
          {
            "id": "clothing.other3",
            "cell": "W10",
            "qty": "U10",
            "total": "V10",
            "size": "T10",
            "free": true
          },
          {
            "id": "clothing.other4",
            "cell": "W11",
            "qty": "U11",
            "total": "V11",
            "size": "T11",
            "free": true
          }
        ]
      }
    ]
  },
  {
    "id": "household",
    "title": "Household",
    "sheet": "xl/worksheets/sheet5.xml",
    "totalCell": "G31",
    "sections": [
      {
        "title": "Bathroom Items",
        "lines": [
          {
            "id": "household.bath_towel_set",
            "label": "Bath Towel Set",
            "cell": "B3",
            "qty": "A3",
            "total": "C3"
          },
          {
            "id": "household.shower_curtain",
            "label": "Shower Curtain",
            "cell": "E3",
            "qty": "D3",
            "total": "F3"
          },
          {
            "id": "household.shower_curtain_liner",
            "label": "Shower Curtain Liner",
            "cell": "H3",
            "qty": "G3",
            "total": "I3"
          },
          {
            "id": "household.in_tub_bathmat",
            "label": "In-tub bathmat",
            "cell": "B4",
            "qty": "A4",
            "total": "C4"
          },
          {
            "id": "household.bathroom_trash_can",
            "label": "Bathroom Trash Can",
            "cell": "E4",
            "qty": "D4",
            "total": "F4"
          },
          {
            "id": "household.bath_mat_rug",
            "label": "Bath Mat/Rug",
            "cell": "H4",
            "qty": "G4",
            "total": "I4"
          }
        ]
      },
      {
        "title": "Kitchen Items",
        "lines": [
          {
            "id": "household.microwave_small",
            "label": "Microwave (small)",
            "cell": "B6",
            "qty": "A6",
            "total": "C6"
          },
          {
            "id": "household.set_of_dishes_4",
            "label": "Set of Dishes (4)",
            "cell": "E6",
            "qty": "D6",
            "total": "F6"
          },
          {
            "id": "household.drinking_glasses_4",
            "label": "Drinking glasses (4)",
            "cell": "H6",
            "qty": "G6",
            "total": "I6"
          },
          {
            "id": "household.coffee_maker",
            "label": "Coffee Maker",
            "cell": "B7",
            "qty": "A7",
            "total": "C7"
          },
          {
            "id": "household.tea_kettle",
            "label": "Tea kettle",
            "cell": "E7",
            "qty": "D7",
            "total": "F7"
          },
          {
            "id": "household.knife_set",
            "label": "Knife Set",
            "cell": "H7",
            "qty": "G7",
            "total": "I7"
          },
          {
            "id": "household.cutting_board",
            "label": "Cutting Board",
            "cell": "B8",
            "qty": "A8",
            "total": "C8"
          },
          {
            "id": "household.silverware_set",
            "label": "Silverware Set",
            "cell": "E8",
            "qty": "D8",
            "total": "F8"
          },
          {
            "id": "household.non_electric_can_opener",
            "label": "Non-electric Can Opener",
            "cell": "H8",
            "qty": "G8",
            "total": "I8"
          },
          {
            "id": "household.spatula",
            "label": "Spatula",
            "cell": "B9",
            "qty": "A9",
            "total": "C9"
          },
          {
            "id": "household.measuring_spoons_cups",
            "label": "Measuring Spoons/cups",
            "cell": "E9",
            "qty": "D9",
            "total": "F9"
          },
          {
            "id": "household.kitchen_tongs",
            "label": "Kitchen Tongs",
            "cell": "H9",
            "qty": "G9",
            "total": "I9"
          },
          {
            "id": "household.cookware_set_to_include_2_saucepans_fryi",
            "label": "Cookware Set (to include 2 saucepans, frying pan, casserole pan)",
            "cell": "B10",
            "qty": "A10",
            "total": "C10"
          },
          {
            "id": "household.kitchen_trash_can",
            "label": "Kitchen Trash Can",
            "cell": "E10",
            "qty": "D10",
            "total": "F10"
          },
          {
            "id": "household.dish_rack",
            "label": "Dish Rack",
            "cell": "H10",
            "qty": "G10",
            "total": "I10"
          },
          {
            "id": "household.food_storage_containers",
            "label": "Food Storage Containers",
            "cell": "B11",
            "qty": "A11",
            "total": "C11"
          },
          {
            "id": "household.potholders",
            "label": "Potholders",
            "cell": "E11",
            "qty": "D11",
            "total": "F11"
          },
          {
            "id": "household.plastic_colander",
            "label": "Plastic Colander",
            "cell": "H11",
            "qty": "G11",
            "total": "I11"
          },
          {
            "id": "household.mixing_bowl",
            "label": "Mixing Bowl",
            "cell": "B12",
            "qty": "A12",
            "total": "C12"
          },
          {
            "id": "household.baking_sheets",
            "label": "Baking sheets",
            "cell": "E12",
            "qty": "D12",
            "total": "F12"
          },
          {
            "id": "household.toaster",
            "label": "Toaster",
            "cell": "H12",
            "qty": "G12",
            "total": "I12"
          }
        ]
      },
      {
        "title": "Bedroom Items",
        "lines": [
          {
            "id": "household.pillows_2",
            "label": "Pillows \u2013 2",
            "cell": "E14",
            "qty": "D14",
            "total": "F14"
          },
          {
            "id": "household.night_light",
            "label": "Night Light",
            "cell": "H14",
            "qty": "G14",
            "total": "I14"
          },
          {
            "id": "household.comforter_set_twin",
            "label": "Twin",
            "cell": "B15",
            "qty": "A15",
            "total": "C15",
            "group": "Comforter Set"
          },
          {
            "id": "household.mattress_protector",
            "label": "Mattress Protector",
            "cell": "E15",
            "qty": "D15",
            "total": "F15"
          },
          {
            "id": "household.lamp_type",
            "label": "Lamp",
            "cell": "H15",
            "qty": "G15",
            "total": "I15",
            "note": true,
            "noteLabel": "Type",
            "text": "Lamp \u2013 Type:"
          },
          {
            "id": "household.comforter_set_twin_xl",
            "label": "Twin XL",
            "cell": "B16",
            "qty": "A16",
            "total": "C16",
            "group": "Comforter Set"
          },
          {
            "id": "household.extra_sheet_set",
            "label": "Extra Sheet Set",
            "cell": "E16",
            "qty": "D16",
            "total": "F16"
          },
          {
            "id": "household.laundry_basket",
            "label": "Laundry Basket",
            "cell": "H16",
            "qty": "G16",
            "total": "I16"
          },
          {
            "id": "household.comforter_set_full_queen",
            "label": "Full/Queen",
            "cell": "B17",
            "qty": "A17",
            "total": "C17",
            "group": "Comforter Set"
          },
          {
            "id": "household.alarm_clock",
            "label": "Alarm Clock",
            "cell": "E17",
            "qty": "D17",
            "total": "F17"
          },
          {
            "id": "household.clothes_hamper",
            "label": "Clothes Hamper",
            "cell": "H17",
            "qty": "G17",
            "total": "I17"
          },
          {
            "id": "household.blanket",
            "label": "Blanket",
            "cell": "B18",
            "qty": "A18",
            "total": "C18"
          },
          {
            "id": "household.plastic_hangers",
            "label": "Plastic Hangers",
            "cell": "H18",
            "qty": "G18",
            "total": "I18"
          },
          {
            "id": "household.long_dresser",
            "label": "Long dresser",
            "cell": "H20",
            "qty": "G20",
            "total": "I20"
          },
          {
            "id": "household.box_spring_standard_height",
            "label": "Standard height",
            "cell": "B21",
            "qty": "A21",
            "total": "C21",
            "group": "Box Spring"
          },
          {
            "id": "household.mattress_twin",
            "label": "Twin",
            "cell": "E21",
            "qty": "D21",
            "total": "F21",
            "group": "Mattress"
          },
          {
            "id": "household.tall_dresser",
            "label": "Tall dresser",
            "cell": "H21",
            "qty": "G21",
            "total": "I21"
          },
          {
            "id": "household.box_spring_low_height",
            "label": "Low height",
            "cell": "B22",
            "qty": "A22",
            "total": "C22",
            "group": "Box Spring"
          },
          {
            "id": "household.mattress_full",
            "label": "Full",
            "cell": "E22",
            "qty": "D22",
            "total": "F22",
            "group": "Mattress"
          },
          {
            "id": "household.nightstand",
            "label": "Nightstand",
            "cell": "H22",
            "qty": "G22",
            "total": "I22"
          }
        ]
      },
      {
        "title": "Furniture",
        "lines": [
          {
            "id": "household.coffee_table_and_end_tables",
            "label": "Coffee table and end tables",
            "cell": "B24",
            "qty": "A24",
            "total": "C24"
          },
          {
            "id": "household.loveseat",
            "label": "Loveseat",
            "cell": "E24",
            "qty": "D24",
            "total": "F24"
          },
          {
            "id": "household.table_and_chairs",
            "label": "Table and chairs",
            "cell": "H24",
            "qty": "G24",
            "total": "I24"
          },
          {
            "id": "household.sofa",
            "label": "Sofa",
            "cell": "B25",
            "qty": "A25",
            "total": "C25"
          },
          {
            "id": "household.chair",
            "label": "Chair",
            "cell": "E25",
            "qty": "D25",
            "total": "F25"
          }
        ]
      },
      {
        "title": "Other Household Items",
        "lines": [
          {
            "id": "household.other1",
            "cell": "B27",
            "qty": "A27",
            "total": "C27",
            "free": true
          },
          {
            "id": "household.other2",
            "cell": "B28",
            "qty": "A28",
            "total": "C28",
            "free": true
          },
          {
            "id": "household.other3",
            "cell": "B29",
            "qty": "A29",
            "total": "C29",
            "free": true
          },
          {
            "id": "household.other4",
            "cell": "B30",
            "qty": "A30",
            "total": "C30",
            "free": true
          }
        ]
      }
    ]
  }
];

/** UHC's furniture price caps. Amounts over a cap are reviewed one by one, not refused. */
export const FURNITURE_CAPS: { label: string; max: number }[] = [
  {
    "label": "Sofa/Loveseat Set",
    "max": 1200.0
  },
  {
    "label": "Sofa",
    "max": 689.0
  },
  {
    "label": "Loveseat",
    "max": 589.0
  },
  {
    "label": "Chair",
    "max": 489.0
  },
  {
    "label": "Sectional",
    "max": 900.0
  },
  {
    "label": "Sectional Converting Bed",
    "max": 1200.0
  },
  {
    "label": "Recliner",
    "max": 399.0
  },
  {
    "label": "Power Recliner",
    "max": 499.0
  },
  {
    "label": "7 Piece Dining set",
    "max": 699.0
  },
  {
    "label": "5 Piece Dining set",
    "max": 499.0
  },
  {
    "label": "3 Piece Dining set",
    "max": 299.0
  },
  {
    "label": "Coffee Table",
    "max": 199.0
  },
  {
    "label": "Side/End Table",
    "max": 99.0
  },
  {
    "label": "TV Stand",
    "max": 299.0
  },
  {
    "label": "5 piece Bedroom set",
    "max": 1750.0
  },
  {
    "label": "Bed Frame & Headboard T/F/Q",
    "max": 499.0
  },
  {
    "label": "Dresser and mirror",
    "max": 649.0
  },
  {
    "label": "5 Drawer Chest",
    "max": 449.0
  },
  {
    "label": "Night Stand",
    "max": 219.0
  },
  {
    "label": "Table Lamp",
    "max": 49.0
  },
  {
    "label": "Floor Lamp",
    "max": 149.0
  },
  {
    "label": "Queen Mattress & Box",
    "max": 599.0
  },
  {
    "label": "Queen Ortho Mattress",
    "max": 449.0
  },
  {
    "label": "Queen Box Spring",
    "max": 219.0
  },
  {
    "label": "Full Mattress & Box",
    "max": 499.0
  },
  {
    "label": "Full Ortho Mattress",
    "max": 399.0
  },
  {
    "label": "Full Box Spring",
    "max": 189.0
  },
  {
    "label": "Twin Mattress & Box",
    "max": 449.0
  },
  {
    "label": "Twin Ortho Mattress",
    "max": 299.0
  },
  {
    "label": "Twin Box Spring",
    "max": 159.0
  }
];

/** Lines whose amount needs the landlord's W-9, invoices and a lease (or a letter). */
export const NEEDS_PAPERWORK: string[] = [
  "services.application_fee",
  "services.security_deposit",
  "services.other_home_deposit",
  "services.water",
  "services.gas",
  "services.electricity",
  "services.telephone",
  "services.oil",
  "services.propane",
  "services.garbage_sewage_service",
  "services.other",
  "services.moving_company"
];
